[build]
# Use Nixpacks (recommended by Railway) to build the project
builder = "nixpacks"
# Install dependencies using uv (project includes uv.lock). Adjust as needed.
# Reproducible builds via the lockfile.
buildCommand = "uv sync --frozen"

[deploy]
# Download runtime plugin/model files on deploy so the worker is ready after start.
# Note: If these files are large and your filesystem is ephemeral, this will re-run on each deploy.
preDeployCommand = ["uv run python -m src.agent download-files"]

# Start the worker in production mode, matching README usage:
# "uv run python src/agent.py start" or "python -m src.agent start"
startCommand = "uv run python -m src.agent start"

# No HTTP server is declared in README; treat as worker process.
# Remove HTTP healthcheck to avoid failing probes.
# If you later expose HTTP, add healthcheckPath and bind to $PORT.
# restartPolicy options: "always" | "on_failure" | "never"
restartPolicyType = "on_failure"
