[build]
# Use Nixpacks (recommended by Railway) to build the project
builder = "nixpacks"
# Install dependencies using uv (project includes uv.lock). Adjust as needed.
# Replace with your actual build steps if different.
buildCommand = "echo building! && uv sync --frozen"

[deploy]
# Optional pre-deploy steps (e.g., migrations). Update or remove as needed.
preDeployCommand = ["echo pre-deploy steps"]

# Start command for your Python app. Update to your actual entrypoint.
# Example for ASGI app with uvicorn (uncomment and adjust if applicable):
# startCommand = "uv run uvicorn src.agent:app --host 0.0.0.0 --port $PORT"
startCommand = "uv run python -m src.agent"

# Healthcheck settings (update path to your app’s health endpoint)
healthcheckPath = "/"
healthcheckTimeout = 100

# Restart policy: "always" | "on_failure" | "never"
restartPolicyType = "on_failure"
